steps:  
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/${PROJECT_ID}/linegpt/linegpt:latest', '.']
  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/${PROJECT_ID}/linegpt/linegpt:latest']

  # Step 3: Deploy the Docker image to Cloud Run, max 2 instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'linegpt', '--image', 'asia-east1-docker.pkg.dev/${PROJECT_ID}/linegpt/linegpt:latest', '--platform', 'managed', '--region', 'asia-east1', '--allow-unauthenticated', '--max-instances', '2', '--memory', '256Mi', '--cpu', '1', '--port', '5000', '--min-instances', '1']
